openapi: 3.1.0
info:
  title: BASE-PT Search API
  version: "1.1.0"
servers:
  - url: https://base-pt-api.onrender.com
paths:
  /search:
    get:
      operationId: searchBase
      summary: Pesquisa datasets/recursos ligados ao Portal BASE no dados.gov.pt (CKAN)
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: Termo de pesquisa (ex.: "Portal BASE contratos públicos 2024")
        - in: query
          name: rows
          required: false
          schema:
            type: integer
            default: 10
        - in: query
          name: start
          required: false
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: Lista de resultados
          content:
            application/json:
              schema:
                type: object
                properties:
                  query: { type: string }
                  count: { type: integer }
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title: { type: string }
                        organization: { type: string, nullable: true }
                        notes: { type: string, nullable: true }
                        metadata_created: { type: string, nullable: true }
                        url: {
